server:
  build: ./
  links:
    - mongo
  ports:
    - "3000:3000"
    - "3030:3030"
  environment:
    - NODE_ENV=development
    - DEBUG=lazyparking-server

mongo:
  image: mongo
  ports:
    - "27017:27017"
