server:
  build: ./
  links:
    - mongodb
  ports:
    - "3000:3000"
    - "3030:3030"
  environment:
    - NODE_ENV=development
    - DEBUG=lazyparking-server
    - MONGODB_NAME=lazyparking-dev

mongodb:
  image: mongo
